############################################################
## 0. Clean environment
############################################################

rm(list = ls())
gc()
graphics.off()

set.seed(1234)


############################################################
## 1. Packages
############################################################

required_packages <- c(
  "Seurat",
  "dplyr",
  "tidyr",
  "tibble"
)

missing_packages <- required_packages[
  !vapply(
    required_packages,
    requireNamespace,
    quietly = TRUE,
    FUN.VALUE = logical(1)
  )
]

if (length(missing_packages) > 0) {
  stop(
    "Please install these packages first: ",
    paste(missing_packages, collapse = ", ")
  )
}

library(Seurat)
library(dplyr)
library(tidyr)
library(tibble)


############################################################
## 2. Paths
############################################################

main_out_dir <- "results_spatial_final"

sensitivity_out_dir <- file.path(
  main_out_dir,
  "Kupffer_threshold_sensitivity"
)

dir.create(
  sensitivity_out_dir,
  showWarnings = FALSE,
  recursive = TRUE
)


############################################################
## 3. Load processed objects
##
## Generated by:
## 01_spatial_main_analysis.R
############################################################

spatial_rds <- file.path(
  main_out_dir,
  "spatial_all_processed.rds"
)

metadata_rds <- file.path(
  main_out_dir,
  "plot_final_spatial_metadata.rds"
)

if (!file.exists(spatial_rds)) {
  stop(
    "Cannot find ",
    spatial_rds,
    ". Run 01_spatial_main_analysis.R first."
  )
}

if (!file.exists(metadata_rds)) {
  stop(
    "Cannot find ",
    metadata_rds,
    ". Run 01_spatial_main_analysis.R first."
  )
}

spatial_all <- readRDS(
  spatial_rds
)

plot_base <- readRDS(
  metadata_rds
)

DefaultAssay(spatial_all) <- "Spatial"


############################################################
## 4. Check required metadata columns
############################################################

required_meta_cols <- c(
  "cell",
  "sample",
  "condition",
  "Kupffer1",
  "Tbk1",
  "Casp1"
)

missing_meta_cols <- setdiff(
  required_meta_cols,
  colnames(plot_base)
)

if (length(missing_meta_cols) > 0) {
  stop(
    "Missing required metadata columns: ",
    paste(missing_meta_cols, collapse = ", ")
  )
}


############################################################
## 5. Fetch sensor expression
############################################################

sensor_genes <- c(
  Aim2 = "Aim2",
  Casp4 = "Casp4",
  Nlrp3 = "Nlrp3"
)

missing_sensor_genes <- setdiff(
  unname(sensor_genes),
  rownames(spatial_all)
)

if (length(missing_sensor_genes) > 0) {
  stop(
    "Missing sensor genes: ",
    paste(missing_sensor_genes, collapse = ", ")
  )
}

sensor_expr <- FetchData(
  spatial_all,
  vars = unname(sensor_genes)
)

colnames(sensor_expr) <- names(sensor_genes)

sensor_expr <- sensor_expr %>%
  rownames_to_column("cell")


############################################################
## 6. Build common dataframe
############################################################

base_df <- plot_base %>%
  select(
    all_of(required_meta_cols)
  ) %>%
  left_join(
    sensor_expr,
    by = "cell"
  ) %>%
  mutate(
    condition = factor(
      condition,
      levels = c(
        "Chow",
        "CDAA-HFD"
      )
    )
  )


############################################################
## 7. Threshold settings
############################################################

threshold_settings <- tibble(
  cutoff = c(
    "Top 5%",
    "Top 10%",
    "Top 15%"
  ),
  quantile_prob = c(
    0.95,
    0.90,
    0.85
  )
)


############################################################
## 8. Safe Fisher exact test
############################################################

safe_fisher_or <- function(
    df,
    group_col,
    outcome_col,
    ref_group,
    target_group
) {
  
  df_sub <- df %>%
    filter(
      .data[[group_col]] %in%
        c(
          ref_group,
          target_group
        )
    )
  
  n_ref <- sum(
    df_sub[[group_col]] == ref_group,
    na.rm = TRUE
  )
  
  n_target <- sum(
    df_sub[[group_col]] == target_group,
    na.rm = TRUE
  )
  
  if (n_ref == 0 || n_target == 0) {
    return(
      tibble(
        OR = NA_real_,
        CI_low = NA_real_,
        CI_high = NA_real_,
        p_value = NA_real_,
        n_ref = n_ref,
        n_target = n_target
      )
    )
  }
  
  tab <- table(
    factor(
      df_sub[[group_col]],
      levels = c(
        ref_group,
        target_group
      )
    ),
    factor(
      df_sub[[outcome_col]],
      levels = c(
        FALSE,
        TRUE
      )
    )
  )
  
  if (!all(dim(tab) == c(2, 2))) {
    return(
      tibble(
        OR = NA_real_,
        CI_low = NA_real_,
        CI_high = NA_real_,
        p_value = NA_real_,
        n_ref = n_ref,
        n_target = n_target
      )
    )
  }
  
  if (
    sum(tab[, "FALSE"]) == 0 ||
    sum(tab[, "TRUE"]) == 0
  ) {
    return(
      tibble(
        OR = NA_real_,
        CI_low = NA_real_,
        CI_high = NA_real_,
        p_value = NA_real_,
        n_ref = n_ref,
        n_target = n_target
      )
    )
  }
  
  ft <- tryCatch(
    fisher.test(tab),
    error = function(e) NULL
  )
  
  if (is.null(ft)) {
    return(
      tibble(
        OR = NA_real_,
        CI_low = NA_real_,
        CI_high = NA_real_,
        p_value = NA_real_,
        n_ref = n_ref,
        n_target = n_target
      )
    )
  }
  
  tibble(
    OR = as.numeric(
      ft$estimate
    ),
    CI_low = as.numeric(
      ft$conf.int[1]
    ),
    CI_high = as.numeric(
      ft$conf.int[2]
    ),
    p_value = ft$p.value,
    n_ref = n_ref,
    n_target = n_target
  )
}


############################################################
## 9. Safe Wilcoxon rank-sum test
############################################################

safe_wilcox <- function(
    df,
    value_col,
    group_col = "condition"
) {
  
  df_test <- df %>%
    filter(
      !is.na(.data[[value_col]]),
      !is.na(.data[[group_col]])
    )
  
  wt <- tryCatch(
    suppressWarnings(
      wilcox.test(
        df_test[[value_col]] ~
          df_test[[group_col]],
        exact = TRUE
      )
    ),
    error = function(e) NULL
  )
  
  if (is.null(wt)) {
    wt <- tryCatch(
      suppressWarnings(
        wilcox.test(
          df_test[[value_col]] ~
            df_test[[group_col]],
          exact = FALSE
        )
      ),
      error = function(e) NULL
    )
  }
  
  if (is.null(wt)) {
    return(
      tibble(
        statistic = NA_real_,
        p_value = NA_real_
      )
    )
  }
  
  tibble(
    statistic = as.numeric(
      wt$statistic
    ),
    p_value = wt$p.value
  )
}


############################################################
## 10. Run one threshold
############################################################

run_threshold_analysis <- function(
    base_df,
    cutoff_label,
    quantile_prob
) {
  
  ##########################################################
  ## A. Define Kupffer-high independently per sample
  ##########################################################
  
  df_thr <- base_df %>%
    group_by(
      sample
    ) %>%
    mutate(
      kup_cut = quantile(
        Kupffer1,
        probs = quantile_prob,
        na.rm = TRUE,
        names = FALSE
      ),
      Kupffer_region_sens = ifelse(
        Kupffer1 >= kup_cut,
        "Kupffer-high",
        "Other"
      )
    ) %>%
    ungroup() %>%
    mutate(
      tbk_casp_state = case_when(
        Tbk1 == 0 &
          Casp1 == 0 ~
          "Tbk1-Casp1-",
        
        Tbk1 == 0 &
          Casp1 > 0 ~
          "Tbk1-Casp1+",
        
        Tbk1 > 0 &
          Casp1 == 0 ~
          "Tbk1+Casp1-",
        
        Tbk1 > 0 &
          Casp1 > 0 ~
          "Tbk1+Casp1+",
        
        TRUE ~ NA_character_
      ),
      
      Aim2_pos = Aim2 > 0,
      Casp4_pos = Casp4 > 0,
      Nlrp3_pos = Nlrp3 > 0
    )
  
  
  ##########################################################
  ## B. Supplementary Table 2 source
  ## Sample-level DP representation
  ##########################################################
  
  double_positive_per_sample <- df_thr %>%
    filter(
      Kupffer_region_sens ==
        "Kupffer-high"
    ) %>%
    group_by(
      condition,
      sample
    ) %>%
    summarise(
      n_double_positive = sum(
        tbk_casp_state ==
          "Tbk1+Casp1+",
        na.rm = TRUE
      ),
      n_kupffer_high = n(),
      frac_double_in_kupffer =
        n_double_positive /
        n_kupffer_high,
      .groups = "drop"
    ) %>%
    mutate(
      cutoff = cutoff_label
    )
  
  
  ##########################################################
  ## Chow vs CDAA-HFD test
  ##########################################################
  
  wilcox_result <- safe_wilcox(
    double_positive_per_sample,
    value_col =
      "frac_double_in_kupffer",
    group_col =
      "condition"
  ) %>%
    mutate(
      cutoff = cutoff_label
    )
  
  
  ##########################################################
  ## C. Supplementary Table 3 source
  ## Sensor enrichment:
  ## DP vs DN
  ##########################################################
  
  sensor_compare_df <- df_thr %>%
    filter(
      condition ==
        "CDAA-HFD",
      Kupffer_region_sens ==
        "Kupffer-high",
      tbk_casp_state %in%
        c(
          "Tbk1-Casp1-",
          "Tbk1+Casp1+"
        )
    )
  
  
  sensor_results <- bind_rows(
    
    safe_fisher_or(
      df = sensor_compare_df,
      group_col = "tbk_casp_state",
      outcome_col = "Aim2_pos",
      ref_group = "Tbk1-Casp1-",
      target_group = "Tbk1+Casp1+"
    ) %>%
      mutate(
        gene = "Aim2"
      ),
    
    safe_fisher_or(
      df = sensor_compare_df,
      group_col = "tbk_casp_state",
      outcome_col = "Casp4_pos",
      ref_group = "Tbk1-Casp1-",
      target_group = "Tbk1+Casp1+"
    ) %>%
      mutate(
        gene = "Casp4"
      ),
    
    safe_fisher_or(
      df = sensor_compare_df,
      group_col = "tbk_casp_state",
      outcome_col = "Nlrp3_pos",
      ref_group = "Tbk1-Casp1-",
      target_group = "Tbk1+Casp1+"
    ) %>%
      mutate(
        gene = "Nlrp3"
      )
  ) %>%
    mutate(
      cutoff = cutoff_label,
      p_adj_BH = p.adjust(
        p_value,
        method = "BH"
      )
    )
  
  
  ##########################################################
  ## D. Supplementary Table 4 source
  ## Casp4 coupling across states
  ##########################################################
  
  casp4_source_df <- df_thr %>%
    filter(
      condition ==
        "CDAA-HFD",
      Kupffer_region_sens ==
        "Kupffer-high"
    )
  
  
  casp4_coupling_results <- bind_rows(
    
    safe_fisher_or(
      df = casp4_source_df,
      group_col = "tbk_casp_state",
      outcome_col = "Casp4_pos",
      ref_group = "Tbk1-Casp1-",
      target_group = "Tbk1-Casp1+"
    ) %>%
      mutate(
        comparison =
          "Tbk1-Casp1+ vs Tbk1-Casp1-"
      ),
    
    safe_fisher_or(
      df = casp4_source_df,
      group_col = "tbk_casp_state",
      outcome_col = "Casp4_pos",
      ref_group = "Tbk1-Casp1-",
      target_group = "Tbk1+Casp1-"
    ) %>%
      mutate(
        comparison =
          "Tbk1+Casp1- vs Tbk1-Casp1-"
      ),
    
    safe_fisher_or(
      df = casp4_source_df,
      group_col = "tbk_casp_state",
      outcome_col = "Casp4_pos",
      ref_group = "Tbk1-Casp1-",
      target_group = "Tbk1+Casp1+"
    ) %>%
      mutate(
        comparison =
          "Tbk1+Casp1+ vs Tbk1-Casp1-"
      )
  ) %>%
    mutate(
      cutoff = cutoff_label,
      p_adj_BH = p.adjust(
        p_value,
        method = "BH"
      )
    )
  
  
  ##########################################################
  ## Return only objects needed for Tables 2–4
  ##########################################################
  
  list(
    double_positive_per_sample =
      double_positive_per_sample,
    
    wilcox_result =
      wilcox_result,
    
    sensor_results =
      sensor_results,
    
    casp4_coupling_results =
      casp4_coupling_results
  )
}


############################################################
## 11. Run all thresholds
############################################################

threshold_results <- lapply(
  seq_len(
    nrow(threshold_settings)
  ),
  function(i) {
    run_threshold_analysis(
      base_df =
        base_df,
      cutoff_label =
        threshold_settings$cutoff[i],
      quantile_prob =
        threshold_settings$quantile_prob[i]
    )
  }
)

names(threshold_results) <-
  threshold_settings$cutoff


############################################################
## 12. Combine threshold results
############################################################

all_double_positive_per_sample <- bind_rows(
  lapply(
    threshold_results,
    `[[`,
    "double_positive_per_sample"
  )
)

all_wilcox <- bind_rows(
  lapply(
    threshold_results,
    `[[`,
    "wilcox_result"
  )
)

all_sensor_results <- bind_rows(
  lapply(
    threshold_results,
    `[[`,
    "sensor_results"
  )
)

all_casp4_coupling <- bind_rows(
  lapply(
    threshold_results,
    `[[`,
    "casp4_coupling_results"
  )
)


############################################################
## 13. Supplementary Table 2
## Representation of Tbk1+Casp1+ spots
############################################################

double_positive_summary <- all_double_positive_per_sample %>%
  group_by(
    cutoff,
    condition
  ) %>%
  summarise(
    n_samples = n(),
    
    total_double_positive =
      sum(n_double_positive),
    
    mean_per_sample =
      mean(n_double_positive),
    
    median_per_sample =
      median(n_double_positive),
    
    Q1 =
      quantile(
        n_double_positive,
        0.25
      ),
    
    Q3 =
      quantile(
        n_double_positive,
        0.75
      ),
    
    min_per_sample =
      min(n_double_positive),
    
    max_per_sample =
      max(n_double_positive),
    
    n_samples_with_zero =
      sum(
        n_double_positive == 0
      ),
    
    .groups = "drop"
  )


supp_table2 <- double_positive_summary %>%
  left_join(
    all_wilcox %>%
      select(
        cutoff,
        `Between-condition P` =
          p_value
      ),
    by = "cutoff"
  ) %>%
  mutate(
    cutoff = factor(
      cutoff,
      levels = c(
        "Top 5%",
        "Top 10%",
        "Top 15%"
      )
    ),
    
    IQR = paste0(
      signif(Q1, 3),
      "–",
      signif(Q3, 3)
    ),
    
    Range = paste0(
      min_per_sample,
      "–",
      max_per_sample
    ),
    
    samples_with_zero = paste0(
      n_samples_with_zero,
      "/",
      n_samples
    )
  ) %>%
  arrange(
    cutoff,
    condition
  ) %>%
  transmute(
    Cutoff =
      as.character(cutoff),
    
    Condition =
      as.character(condition),
    
    `Total double-positive spots` =
      total_double_positive,
    
    `Mean spots/sample` =
      round(
        mean_per_sample,
        2
      ),
    
    `Median spots/sample` =
      round(
        median_per_sample,
        2
      ),
    
    IQR =
      IQR,
    
    Range =
      Range,
    
    `Samples with zero DP spots` =
      samples_with_zero,
    
    `Between-condition P` =
      signif(
        `Between-condition P`,
        4
      )
  )


############################################################
## 14. Supplementary Table 3
## Sensor enrichment sensitivity
############################################################

supp_table3 <- all_sensor_results %>%
  mutate(
    cutoff = factor(
      cutoff,
      levels = c(
        "Top 5%",
        "Top 10%",
        "Top 15%"
      )
    ),
    
    gene = factor(
      gene,
      levels = c(
        "Aim2",
        "Casp4",
        "Nlrp3"
      )
    ),
    
    Sensor = recode(
      as.character(gene),
      "Aim2" =
        "Aim2",
      "Casp4" =
        "Casp4 (Casp11)",
      "Nlrp3" =
        "Nlrp3"
    ),
    
    `95% CI` = paste0(
      signif(
        CI_low,
        3
      ),
      "–",
      signif(
        CI_high,
        3
      )
    )
  ) %>%
  arrange(
    cutoff,
    gene
  ) %>%
  transmute(
    Cutoff =
      as.character(cutoff),
    
    Sensor =
      Sensor,
    
    OR =
      round(
        OR,
        3
      ),
    
    `95% CI` =
      `95% CI`,
    
    `Raw P` =
      signif(
        p_value,
        4
      ),
    
    `BH-adjusted P` =
      signif(
        p_adj_BH,
        4
      ),
    
    `Reference spots` =
      n_ref,
    
    `Target spots` =
      n_target
  )


############################################################
## 15. Supplementary Table 4
## Casp4 coupling sensitivity
############################################################

supp_table4 <- all_casp4_coupling %>%
  mutate(
    cutoff = factor(
      cutoff,
      levels = c(
        "Top 5%",
        "Top 10%",
        "Top 15%"
      )
    ),
    
    comparison_order = case_when(
      comparison ==
        "Tbk1-Casp1+ vs Tbk1-Casp1-" ~ 1,
      
      comparison ==
        "Tbk1+Casp1- vs Tbk1-Casp1-" ~ 2,
      
      comparison ==
        "Tbk1+Casp1+ vs Tbk1-Casp1-" ~ 3,
      
      TRUE ~ 99
    ),
    
    Comparison = recode(
      comparison,
      
      "Tbk1-Casp1+ vs Tbk1-Casp1-" =
        "Tbk1−Casp1+ vs Tbk1−Casp1−",
      
      "Tbk1+Casp1- vs Tbk1-Casp1-" =
        "Tbk1+Casp1− vs Tbk1−Casp1−",
      
      "Tbk1+Casp1+ vs Tbk1-Casp1-" =
        "Tbk1+Casp1+ vs Tbk1−Casp1−"
    ),
    
    `95% CI` = paste0(
      signif(
        CI_low,
        3
      ),
      "–",
      signif(
        CI_high,
        3
      )
    )
  ) %>%
  arrange(
    cutoff,
    comparison_order
  ) %>%
  transmute(
    Cutoff =
      as.character(cutoff),
    
    Comparison =
      Comparison,
    
    OR =
      round(
        OR,
        3
      ),
    
    `95% CI` =
      `95% CI`,
    
    `Raw P` =
      signif(
        p_value,
        4
      ),
    
    `BH-adjusted P` =
      signif(
        p_adj_BH,
        4
      ),
    
    `Reference spots` =
      n_ref,
    
    `Target spots` =
      n_target
  )


############################################################
## 16. Print final tables
############################################################

cat(
  "\nSupplementary Table 2:\n"
)

print(
  supp_table2,
  n = Inf,
  width = Inf
)

cat(
  "\nSupplementary Table 3:\n"
)

print(
  supp_table3,
  n = Inf,
  width = Inf
)

cat(
  "\nSupplementary Table 4:\n"
)

print(
  supp_table4,
  n = Inf,
  width = Inf
)


############################################################
## 17. Save Supplementary Tables 2–4
############################################################

write.csv(
  supp_table2,
  file.path(
    sensitivity_out_dir,
    "Supplementary_Table_2_threshold_representation.csv"
  ),
  row.names = FALSE
)

write.csv(
  supp_table3,
  file.path(
    sensitivity_out_dir,
    "Supplementary_Table_3_sensor_enrichment_sensitivity.csv"
  ),
  row.names = FALSE
)

write.csv(
  supp_table4,
  file.path(
    sensitivity_out_dir,
    "Supplementary_Table_4_Casp4_coupling_sensitivity.csv"
  ),
  row.names = FALSE
)


############################################################
## 18. Save session information
############################################################

writeLines(
  capture.output(
    sessionInfo()
  ),
  con = file.path(
    sensitivity_out_dir,
    "sessionInfo_threshold_sensitivity.txt"
  )
)


############################################################
## 19. Final message
############################################################

cat(
  "\nThreshold sensitivity analysis completed.\n"
)

cat(
  "Outputs saved to:\n",
  sensitivity_out_dir,
  "\n"
)